#!/bin/bash 

echo -e "Created:\n$1.h\n$1.c\n$1_test.c"

mkdir $1
touch $1/$1.h
touch $1/$1.c
touch $1/$1_test.c

echo -e "/****************************************
 * Title  : 	     					 *
 * Author : 			                 *
 * Group  : OL712						 *
 * Date   : 			               	 *
 ****************************************/" >> $1/$1.h
echo -e "#ifndef __ILRD_OL712_${1^^}_H" >> $1/$1.h
echo -e "#define __ILRD_OL712_${1^^}_H" >> $1/$1.h
echo -e "\n#endif /* __ILRD_OL712_${1^^}_H */" >> $1/$1.h

echo -e "#include <stdio.h>\n#include <assert.h>\n\n#include \"$1.h\"" >> $1/$1_test.c
echo -e "\n/****************************\n *   Author   : Ran Shieber *\n *   Reviewer : 		    *\n *	 Status   : Sent	    *\n ****************************/\n" >> $1/$1.c
echo -e "#include \"$1.h\"\n" >> $1/$1.c

cat /home/student0/ran-shieber/scripts/test_template.c >> $1/$1_test.c

echo -e "CC=gcc

RELEASE_FLAGS=-ansi -pedantic-errors -Wall -Wextra -DNDEBUG -O3
DEBUG_FLAGS=-ansi -pedantic-errors -Wall -Wextra -g

DEPS= $1_test.c $1.c

all: $1_release $1_debug

$1_release: $1.c $1_test.c
	\$(CC) \$(RELEASE_FLAGS) \$(DEPS) -o $1_release.out

$1_debug: $1.c $1_test.c
	\$(CC) \$(DEBUG_FLAGS) \$(DEPS) -o $1_debug.out

val: $1.c $1_test.c
	\$(CC) \$(DEBUG_FLAGS) \$(DEPS) -o $1_debug.out && valgrind --leak-check=yes --track-origins=yes ./$1_debug.out

clean:
	rm -f *.out" > $1/makefile
